kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  namespace: jboss-handson
  name: weather-bc
  labels:
    build: weather-bc
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'weather-bc:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    dockerStragety:
      env: {}
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'jboss-eap73-openjdk11-openshift:7.3'
    type: Docker
  source:
    git:
      ref: "main"
      uri: 'https://github.com/edubois10/jboss-dockerfile-build.git'
#    sourceSecret: {}
    type: Git
  triggers: []
  runPolicy: Serial
