kind: BuildConfig
apiVersion: build.openshift.io/v1
metadata:
  name: weather-app
  namespace: jboss-handson
  labels:
    build: weather-app
spec:
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: 'weather-app:latest'
  resources: {}
  successfulBuildsHistoryLimit: 5
  failedBuildsHistoryLimit: 5
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        namespace: openshift
        name: 'jboss-eap73-openjdk11-openshift:7.3'
  postCommit: {}
  source:
    type: Binary
    binary: {}
  triggers:
    - type: GitHub
      github:
        secret: qnBeRQUG-2GV-j7_8rlr
    - type: Generic
      generic:
        secret: sPbq1JhQ1iyaEH93RmgQ
  runPolicy: Serial